In [7]:
from formulas.running import *
import wilson
import numpy as np

# Running in the High-energy theory

## $c_{uR}$

In [2]:
clow_uR = match_run({'cuR': 1.0}, 5000, 1000)

/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  c12 = cos(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:25: ComplexWarning: Casting complex values to real discards the imaginary part
  c23 = cos(t23)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:26: ComplexWarning: Casting complex values to real discards the imaginary part
  s12 = sin(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:28: ComplexWarning: Casting complex values to real discards the imaginary part
  s23 = sin(t23)


In [3]:
clow_ur_ll = match_run({'cuR': 1.0}, 5000, 1000, True)

In [4]:
clow_uR

{'cqL': matrix([[ 7.39308109e-03-1.06254788e-23j,
          -4.15223158e-06-1.73282704e-06j,
           1.02643979e-04+4.10225154e-05j],
         [-4.15223158e-06+1.73282704e-06j,
           7.41261986e-03+1.40687142e-23j,
          -5.04057747e-04+9.44166042e-06j],
         [ 1.02643979e-04-4.10225154e-05j,
          -5.04057747e-04-9.44166042e-06j,
           1.98844451e-02-1.18203026e-25j]]),
 'cuR': matrix([[ 9.17503255e-01-6.95823650e-23j,
           4.44781661e-21-5.66718491e-21j,
          -1.18393835e-15+3.86264272e-15j],
         [ 4.44781661e-21+5.66718491e-21j,
           9.17502875e-01-6.95820704e-23j,
          -2.36199592e-11+5.68580608e-16j],
         [-1.18393835e-15-3.86264272e-15j,
          -2.36199592e-11-5.68580608e-16j,
           8.92476111e-01+5.36483361e-24j]]),
 'cdR': matrix([[ 6.76828423e-02+6.93412809e-23j,
          -3.11082936e-16-1.29833364e-16j,
           4.08219524e-13+1.63148047e-13j],
         [-3.11082936e-16+1.29833364e-16j,
           6.76828422e

In [5]:
clow_ur_ll

{'cqL': matrix([[ 7.27986493e-03+0.00000000e+00j,
          -4.37780375e-06-1.82741205e-06j,
           1.08113684e-04+4.32083267e-05j],
         [-4.37780375e-06+1.82741205e-06j,
           7.30046571e-03+0.00000000e+00j,
          -5.30917034e-04+9.94475873e-06j],
         [ 1.08113684e-04-4.32083267e-05j,
          -5.30917034e-04-9.94475873e-06j,
           2.04204690e-02+0.00000000e+00j]]),
 'cuR': matrix([[9.13715169e-01-3.79843521e-22j, 9.17458924e-26+5.30201262e-27j,
          4.43799975e-24+3.37221175e-24j],
         [9.17458924e-26-5.30201262e-27j, 9.13714778e-01-3.79843521e-22j,
          8.95323755e-19+3.53627289e-18j],
         [4.43799975e-24-3.37221175e-24j, 8.95323755e-19-3.53627289e-18j,
          8.87386902e-01-3.79843521e-22j]]),
 'cdR': matrix([[0.07170314+3.79843521e-22j, 0.        +0.00000000e+00j,
          0.        +0.00000000e+00j],
         [0.        -0.00000000e+00j, 0.07170314+3.79843521e-22j,
          0.        +0.00000000e+00j],
         [0.        -0.0

The leading log approximation reproduces well the exact results

If we only retain the yukawa of the top, the beta functions are

$$\beta_{c_{qL}^{ii}} = -y_t^2 c_{uR}^{33}\delta_{i3} - 8\alpha_s^2 \mathrm{tr}(c_{uR})-\frac{4}{9}\alpha_1^2 \mathrm{tr}(c_{uR})$$
$$\beta_{c_{uR}^{ii}} = 2y_t^2(\delta_{i3}+3)+8\alpha_s^2 \mathrm{tr}(c_{uR}) + \frac{64}{9}\alpha_1^2 \mathrm{tr}(c_{uR})$$
$$\beta_{c_{dR}^{ii}} = -6 y_t^2 c_{uR}^{33} + 16 \alpha_s^2 \mathrm{tr}(c_{uR}) -\frac{4}{3}\alpha_1^2 \mathrm{tr}(c_{uR}) $$
$$\beta_{c_{\ell L}^{ii}} =  -4\alpha_1^2 \mathrm{tr}(c_{uR})$$
$$\beta_{c_{eR}^{ii}} =  -6 y_t^2 c_{uR}^{33}+4\alpha_1^2 \mathrm{tr}(c_{uR})$$

In [8]:
wSM = wilson.classes.SMEFT(wilson.wcxf.WC('SMEFT', 'Warsaw', 5000, {})).C_in
yt = wSM['Gu'][2,2]
alpha_s = wSM['gs']**2/(4*np.pi)
alpha_1 = wSM['gp']**2/(4*np.pi)
alpha_2 = wSM['g']**2/(4*np.pi)

/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  c12 = cos(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:25: ComplexWarning: Casting complex values to real discards the imaginary part
  c23 = cos(t23)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:26: ComplexWarning: Casting complex values to real discards the imaginary part
  s12 = sin(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:28: ComplexWarning: Casting complex values to real discards the imaginary part
  s23 = sin(t23)


In [15]:
beta0 = column2dict(beta(5000, dict2column({'cuR': 1.0}))*(16*np.pi**2))

/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  c12 = cos(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:25: ComplexWarning: Casting complex values to real discards the imaginary part
  c23 = cos(t23)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:26: ComplexWarning: Casting complex values to real discards the imaginary part
  s12 = sin(t12)
/home/jorge/.local/lib/python3.12/site-packages/ckmutil/ckm.py:28: ComplexWarning: Casting complex values to real discards the imaginary part
  s23 = sin(t23)


In [20]:
np.diag(beta0['cqL'])

array([-0.1444631 +0.j, -0.14560464+0.j, -0.79858   +0.j])

In [14]:
-yt**2*np.array([0,0,1]) + (-8*alpha_s**2*3-4/9*alpha_1**2*3)*np.array([1, 1, 1])

array([-0.1444054 +0.0000000e+00j, -0.1444054 +0.0000000e+00j,
       -0.79857999-1.7959203e-16j])

In [23]:
np.diag(beta0['cuR'])

array([4.07926125-1.69402742e-20j, 4.07927868-1.69402742e-20j,
       5.39010688-1.69402742e-20j])

In [24]:
2*yt**2*np.array([3, 3, 4]) + (8*alpha_s**2*3+64/9*alpha_1**2*3)*np.array([1, 1, 1])

array([4.07171952+1.07755218e-15j, 4.07171952+1.07755218e-15j,
       5.38006869+1.43673624e-15j])

In [25]:
np.diag(beta0['cdR'])

array([-3.78773049+1.69402742e-20j, -3.78773049+1.69402742e-20j,
       -3.78773049+1.69402742e-20j])

In [33]:
3*16*alpha_s**2-3*4*alpha_1**2/3-6*yt**2

(-3.6369922294344277-1.0775521777416848e-15j)

In [29]:
12*(3**2-1)/(2*3)

16.0

In [30]:
np.diag(beta0['clL'])

array([-0.00135997+0.j, -0.00135997+0.j, -0.00135997+0.j])

In [31]:
-4*alpha_1**2*3

(-0.0013599734476001464+0j)

In [32]:
np.diag(beta0['ceR'])

array([-3.92714932+1.69402742e-20j, -3.92714932+1.69402742e-20j,
       -3.92714932+1.69402742e-20j])

In [34]:
-6*yt**2+4*alpha_1**2*3

(-3.9236875241820512-1.0775521777416848e-15j)